FROM quay.io/fedora/fedora:44

ARG OGX_VERSION=1.0.0

RUN dnf -y install uv gcc python3-devel git && \
    dnf -y clean all

RUN uv venv && \
    uv pip install ogx==${OGX_VERSION}

COPY --chmod=755 container-images/llama-stack/entrypoint.sh /usr/bin/entrypoint.sh

COPY container-images/llama-stack/ramalama-run.yaml /opt/ramalama/etc/ramalama-run.yaml

# see https://ogx-ai.github.io/docs/distributions/building_distro#air-gapped-and-disconnected-deployments
ENV TIKTOKEN_CACHE_DIR="/opt/ramalama/var/tiktoken"
RUN mkdir /opt/ramalama/var && \
    uv run python -c "import tiktoken; tiktoken.get_encoding('cl100k_base')"

ENTRYPOINT [ "/usr/bin/entrypoint.sh" ]

CMD [ "ogx",  "stack",  "run", "/opt/ramalama/etc/ramalama-run.yaml" ]
